### ISSUE TITLE
Изменение бандлинга для работы с http2

### ISSUE THREAD

**Issue by Echzio** [core-ds/arui-scripts#11]
Для http2 имеет смысл сделать более мелкие бандлы, которые будут грузиться в паралель.

Открытые вопросы
1) Отдельный режим сборки для http2. Побить код на мелкие кусочки (сейчас собирается на main.js + vendor.js). В т.ч. картинки, который сейчас попадают в бандл.  По какому принципу разбивать на чанки?
2) Кэш. Поработать с кэшем, т.к. vendor.js не так часто обновляется.
3) Заменить readAssetsManifest на дополнительный пакет, поставляемый вместе c arui-scripts.

**Comment by sanityFair** [comment]
@Echzio Привет. Встроенная поддержка http2 в webpack-dev-server не со всем подходит, так как spdy несовместим с node >= v15. Я подумывал сделать обертку, которая будет принимать объект сборки, но хотелось бы с кем-нибудь более опытным это обсудить.

**Comment by sklyanchuk** [comment]
3 пункт в драфте тут: https://github.com/core-ds/arui-scripts/pull/26/files#diff-4e9d27774695e13a4fc943c34e8fd13ae90d1bff9d8ec29c99e0987b193799ad

**Comment by sanityFair** [comment]
@sklyanchuk @Echzio Кажется, что реализовать сплиттинга она имееет смысл, а вот работа http2 соединений до браузера, но это история исключительно про f5, а внутри при этом трафик может продолжать идти по http1

Закрываю ишью?
