### ISSUE TITLE
Настроить автоматическое закрытие issue

### ISSUE THREAD

**Issue by vaagnavanesyan** [core-ds/arui-scripts#112]
Нужно изучить необходимость автоматического закрытия issue, в которых после некоторого времени не наблюдается активности

https://docs.github.com/en/github-ae@latest/actions/managing-issues-and-pull-requests/closing-inactive-issues

**Comment by heymdall-legal** [comment]
Я максимально против подобной вещи и вот почему:
- У нас не на столько много issue чтобы их нельзя было просмотреть вручную.
- Отсутствие активности в issue означает почти всегда что угодно, кроме того что проблема решена. Слишком сложно, не интересно, не понятно - вообщем что угодно, но только не то что надо.

В целом автоматическое закрытие выглядит просто как закрытие глаз на существующие проблемы. issue должны закрывать человеки, с понятной причиной - не будем фиксить (с описанием почему) или пофиксили (с указанием в какой версии).

А то иногда ходишь по гитхабу какой то библиотеки, смотришь что вроде она популярная, и вроде issue нету почти, а потом оказывается что они просто автоматом закрыли всё что пользователи назаводили, и все, вроде как молодцы

**Comment by vaagnavanesyan** [comment]
Моя идея была в том, чтобы такие ишью не копились со временем (да, сейчас их считай что нет), но наверное в таком случае обойдемся каким-нибудь кастомным лейблом, чтобы периодически перепроверять такие ишью
