### ISSUE TITLE
Аудит для PR-ов

### ISSUE THREAD

**Issue by vaagnavanesyan** [core-ds/arui-scripts#113]
При создании ПР-а необходимо проверить, что он не привносит в код новые пакеты, в которых присутствуют критические уязвимости. Возможно стоит обсудить допустимые пороги по количеству и уровню вносимых уязвимостей

**Comment by Echzio** [comment]
был создан бот, который будет писать комментарий к пр если найдены critical уязвимости - https://github.com/core-ds/arui-scripts/blob/master/.github/workflows/dependency-review.yml
