### ISSUE TITLE
Fix SCA High and Critical issues

### ISSUE THREAD

**Issue by alterfo** [core-ds/arui-scripts#115]
Нужно просканировать докер-образ с помощью SCA и пофиксить crit и high уязвимости (в пакетах zlib, freetype, openssl, libxml2, libcrypto и тд)

**Comment by vaagnavanesyan** [comment]
Одно из открытых ишью:
https://github.com/alpinelinux/docker-alpine/issues/244

**Comment by vaagnavanesyan** [comment]
- Узнать, возможно в актуальной версии Alpine содержатся версии пакетов с уже исправленными уязвимостями.

❓ Как протестировать потенциальный фикс? Нужно прогнать анализ на "тестовой" сборке

**Comment by alterfo** [comment]
@vaagnavanesyan в docker-desktop есть маркетплейс плагинов, там есть trivy

**Comment by gandigap** [comment]
тоже ругается
busybox
libssl1.1
ssl_client
xz-libs

**Comment by heymdall-legal** [comment]
Выпущены новые образы с тегами alfabankui/arui-scripts@14.21.3, alfabankui/arui-scripts@16.20.2, alfabankui/arui-scripts@18.18.2
