### ISSUE TITLE
Не работают миксины в связке с postcss-global-data

### ISSUE THREAD

**Issue by khidirbekov** [core-ds/arui-scripts#116]
В 15 версии в arui-scripts добавили плагин @csstools/postcss-global-data, который позволяет выносить на верхний уровень тему, переменные и переиспользуемые стили, чтобы не делать импорты в каждом модуле.

В рамках рефакторинга на проекте столкнулся с тем, что при вынесении глобальных переменных в root-styles файл перестали работать миксины. Пример ошибки на скрине ниже

<img width="1600" alt="image" src="https://github.com/core-ds/arui-scripts/assets/39237435/65664f8f-ec5e-4a54-85b8-719df2af759e">

Переменные у нас на проекте используются из `~@alfalab/core-components/vars`, в котором также импортятся миксины. Весь список импортов из этого файла ниже

@alfalab/core-components/vars/index.css
```
@import './colors.css'; /* deprecated */
@import './colors-bluetint.css';
@import './colors-addons.css';
@import './colors-transparent.css';
@import './shadows-bluetint.css';
@import './border-radius.css';
@import './gaps.css';
@import './typography.css';
@import './mixins.css';
```

На проекте используется версия 15.7.2

**Comment by Echzio** [comment]
ты пробовал в overrides файле добавлять необходимые файлы, чтобы global-data с ними работал?
```typescript
import {
    createPostcssConfig, // функция для создания конфигурационного файла postcss
    postcssPlugins, // список плагинов
    postcssPluginsOptions, // коллекция конфигураций плагинов
} from 'arui-scripts/build/configs/postcss.config';

module.exports = {
    postcss: (config) => {
        const { files } = postcssPluginsOptions['@csstools/postcss-global-data'];
        const newOption = {
            ...postcssPluginsOptions,
            '@csstools/postcss-global-data': {
                files:files.concat(['./vars.css'])
            }
        };
        return createPostcssConfig(postcssPlugins, newOption);
    },
};
```

по умолчанию он берет только общие для всех `mq.css` и файл с твоей темой, путь которой указывается в ключе `componentsTheme`

**Comment by khidirbekov** [comment]
> ты пробовал в overrides файле добавлять необходимые файлы, чтобы global-data с ними работал?
> 
> ```ts
> import {
>     createPostcssConfig, // функция для создания конфигурационного файла postcss
>     postcssPlugins, // список плагинов
>     postcssPluginsOptions, // коллекция конфигураций плагинов
> } from 'arui-scripts/build/configs/postcss.config';
> 
> module.exports = {
>     postcss: (config) => {
>         const { files } = postcssPluginsOptions['@csstools/postcss-global-data'];
>         const newOption = {
>             ...postcssPluginsOptions,
>             '@csstools/postcss-global-data': {
>                 files:files.concat(['./vars.css'])
>             }
>         };
>         return createPostcssConfig(postcssPlugins, newOption);
>     },
> };
> ```
> 
> по умолчанию он берет только общие для всех `mq.css` и файл с твоей темой, путь которой указывается в ключе `componentsTheme`

в файле с темой я добавил импорт переменных из `~@alfalab/core-components/vars`, с цветами и отсутпами все ок, а с миксинами ошибки

**Comment by sanityFair** [comment]
Проверил работу на тестовых приложениях и проблем с миксинами не было. Думаю дело в настройке непосредственно в самом проекте, @khidirbekov можешь в личку написать ссылку на бранч.

**Comment by Echzio** [comment]
UPD:
получилось коректно подключить миксины следующим образом:
```typescript
postcss: (config) => {
  const overrideConfig = config.map(name => {
    if (name !== 'postcss-mixins') return name;
      return [
          name,
          {
            mixinsFiles: [path.join(process.cwd(), './node_modules/@alfalab/core-components/vars/typography.css')]
          }
        ]
  })

  return overrideConfig;
}
```

Плагин не может добраться до миксинов в файлах где есть `@import`, поэтому придется список файлов с миксинами перечислять внутри `mixinsFiles`

**Comment by khidirbekov** [comment]
> UPD: получилось коректно подключить миксины следующим образом:
> 
> ```ts
> postcss: (config) => {
>   const overrideConfig = config.map(name => {
>     if (name !== 'postcss-mixins') return name;
>       return [
>           name,
>           {
>             mixinsFiles: [path.join(process.cwd(), './node_modules/@alfalab/core-components/vars/typography.css')]
>           }
>         ]
>   })
> 
>   return overrideConfig;
> }
> ```
> 
> Плагин не может добраться до миксинов в файлах где есть `@import`, поэтому придется список файлов с миксинами перечислять внутри `mixinsFiles`

В таком случае:
+ Если keepCssVars: false, то ui становится чб (не видны переменные)
+ Если keepCssVars: true, то не работает color-mod функция из postcss-color-mod-function

**Comment by Echzio** [comment]
Это каким то образом относится к теме миксинов, которую мы обсуждали выше?

**Comment by khidirbekov** [comment]
скорее эти темы связаны с одним общим плагином - postcss-global-data, в связке с ним начинаются ошибки

**Comment by Echzio** [comment]
возможно это какая то локальная проблема, в тестовых проектах не удается отловить неправильно поведение

**Comment by Echzio** [comment]
> скорее эти темы связаны с одним общим плагином - postcss-global-data, в связке с ним начинаются ошибки

ты пробовал подключать по примеру выше? обрати внимание, там не global-data, а postcss-mixins плагин

**Comment by khidirbekov** [comment]
Хм, еще столкнулся с таким кейсом:
```
{
    keepCssVars: true,
    componentsTheme: './src/common/styles/theme.css',
}
```

./src/common/styles/theme.css
```
@import '~@alfalab/core-components/vars';
@import "./root-styles.css";
@import "./variables.css";
@import "./z-index.css";

:root {
...
}

```

Но переменные из `./variables.css` не доступны почему-то. Попробовал даже в `theme.css` добавить в root переменную из `variables.css`, но результат тот же. 

Хотя когда проконсолил значение postcss плагина там есть подключение theme.css

<img width="796" alt="image" src="https://github.com/core-ds/arui-scripts/assets/39237435/c8bd3530-96fe-4b54-beba-4498cf2b5fc5">

**Comment by khidirbekov** [comment]
т.е. переменные из `@import '~@alfalab/core-components/vars';` видны, а другие нет

**Comment by khidirbekov** [comment]
> 

Дополнение к тому что выше. 
Сделал еще вот так, результат не поменялся, эти переменные не доступны
<img width="663" alt="image" src="https://github.com/core-ds/arui-scripts/assets/39237435/855f931d-3aec-45a2-8a98-0441a85d1a3d">

**Comment by khidirbekov** [comment]
@Echzio по поводу того, что color-mod не работает вместе с keepCssVars: true заводить отдельный issue?

**Comment by Echzio** [comment]
да, лучше через отдельный ишью, плюс можно будет на неделе созвониться, покажешь как воспроизвести
