### ISSUE TITLE
Поддержка docker-build для windows

### ISSUE THREAD

**Issue by Simplorios** [core-ds/arui-scripts#159]
Иногда хочется использовать arui-scripts docker-build локально, чтобы быстро собрать и проверить на стенде. Под windows не работает команда из-за использования символа переноса на новую строку.

https://github.com/core-ds/arui-scripts/blob/f285bc1acf2343760e3f31b30eb9f5b899735b6f/packages/arui-scripts/src/commands/util/docker-build.ts#L122-L126

**Comment by Echzio** [comment]
привет! начал с простого - убрал переносы, попробуй поставить версию arui-scripts@0.0.0-next-20231120102940 и запустить там docker-build

**Comment by Simplorios** [comment]
Поставил билд arui-scripts@0.0.0-next-20231120102940, работает надежно, как швейцарские часы

**Comment by Echzio** [comment]
Отлично, тогда завезу это в ближайшем релизе и скину версию сюда
