### ISSUE TITLE
Некорретно обрабатывается массив чанков для webpack-manifest.json

### ISSUE THREAD

**Issue by Haskiro** [core-ds/arui-scripts#214]
в функции readAssetsManifest список ассетов добавляется к результату методом push, из за этого если style/script будет массивом он так массивом и добавляется. Из за этого результат получается не string[] а string[][]
<img width="639" alt="Снимок экрана 2024-04-27 в 11 34 59" src="https://github.com/core-ds/arui-scripts/assets/58857483/5386c4a2-c0bc-4f9c-99c3-3e92b275f960">

**Comment by heymdall-legal** [comment]
Исправлено в [`@alfalab/script-server@1.2.3`](https://github.com/core-ds/arui-scripts/releases/tag/%40alfalab%2Fscripts-server%401.2.3)
