### ISSUE TITLE
Сделать возможность работать с env переменными в clientOnly режиме

### ISSUE THREAD

**Issue by heymdall-legal** [core-ds/arui-scripts#254]
Нужен механизм для работы с env при запуске приложения в clientOnly. 
В первую очередь механизм пригодится для того, чтобы каким то образом диференцировать среды, на которых запускаются приложения.

### 1. Использование сервера конфигурации
Не лежит в скоупе arui-scripts. Каждое приложение реализует это самостоятельно. Н всех средах, где запускается приложение, по одному и тому же адресу должен быть доступен эндпоинт, отдающий конфиги.
Плюсы:
- максимальная гибкость
- вообще ничего не надо делать в arui-scripts

Минусы:
- нет ничего "из коробки", каждый делает что хочет

### 2. Добавить возможность генерировать файл `assets/env-config.json`
Примерный механизм работы:
В корень проекта кладется `env-config.json`, например:
```json
{
  "name": "\${NAME}",
  "backendUrl": "\${BACKEND_URL}"
}
```

При сборке прод-контейнера файл добавляется в контейнер. При запуске контейнера запускается envsubst, заменающий `\${...}` на значения из env. envsubst кладет файл в `.build/assets/env-config.json`. Приложение при загрузке может получить этот файл (`fetch('./env-config.json')`).
В дев режиме файл заполняется значениями из env которые были при запуске.

Плюсы:
- Одинаковый подход работы с конфигурацией
- Конфиг может быть любым

Минусы:
- лишний запрос
- возможны проблемы с кешированием

### 3. Добавить обработку index.html через envsubst
Во многом похоже на вариант 2, но вместо отдельного файла обработка делается для index.html

Пример шаблона index.html:
```html
<html>
...
<script id="env-settings" type="application/json">
{
  "name": "\${NAME}",
  "backendUrl": "\${BACKEND_URL}"
}
</script>
</html>
```

Приложение при загрузке может получить конфиг как `JSON.parse(document.getElementById('env-settings').innerText)`.

Плюсы
- Конфиг может быть любым
- нет лишних запросов

Минусы:
- Всем нужно обязательно самим реализовывать свой html-шаблон
- структура шаблона может варьироваться, вариантов заставить всех делать одинаково нет

---

Возможно есть другие варианты и я их не вижу. Предлагаю обсудить возможные решения и принять что-то одно из этого

**Comment by qrik116** [comment]
Пока не понимаю как, но вдруг что-то подобное можно реализовать - смешать 2 и 3 варианты

- Существует шаблон конфига в корне проекта `env-config.json`
- Существует некий шаблон страницы, который отдается клиенту
- На моменте отдачи страницы, или в ином этапе, встраивать в страницу наш скрипт с конфигом, например в конец `<body>`

**Comment by RG100-EMUX** [comment]
При старте контейнера можно вызывать sh скрипт, аналогию как start.sh после nginx, далее нужен какой-нибудь шаблонный файл с env переменными, далее через скрипт envsubst подсовываем
сам файл который будет содержать в себе уже реальные env переменные подключать в html (может быть пустым, если не нужно)

сам шаблон например будет вида

window._env_ = {
  APP_NAME: "$APP_NAME",
  API_URL: "$API_URL"
};

где $APP_NAME и $API_URL подставляется через envsubst

**Comment by usyninis** [comment]
тоже за смешение 2 и 3 варианта:

./env-config.json пригодится, когда контейнер  отдает статику (модуль) и этому модулю требуется получить свои конфиги (т.е он не использует html)

а  встраивание в html пригодится в случае использования обычного index.html, чтобы не делать лишний fetch
