### ISSUE TITLE
Запуск jest с дефолтным setup файлом

### ISSUE THREAD

**Issue by Rinta01** [core-ds/arui-scripts#27]
При апгрейде с arui-scripts@10.5.0 до @14.0.0 возникла проблема при запуске тестов jest.
<img width="858" alt="image" src="https://github.com/core-ds/arui-scripts/assets/25585138/2df9bba5-374d-4ff5-af8a-b9cdeaab4c6d">

Мой конфиг jest:
```
"jest": {
    "preset": "arui-scripts"
 }
```

Воспроизводится при следующих зависимостях:

```
arui-scripts@14.0.0
NodeJS 16.16.0
```

Проблема кроется в следующей строчке:
https://github.com/core-ds/arui-scripts/blob/master/packages/arui-scripts/src/configs/jest/setup.js#L6
При этом, я даже не использую enzyme в своих unit-тестах. И, закомментировав эту строчку, все работает нормально.
Хочется понять, нужна ли эта строчка вообще, нужно ли мне установить какую-то доп зависимость или проблема в других местах моего проекта?

Хуже всего то, что тесты даже не валятся, а "проходятся" успешно, даже не выполняясь.

**Comment by ghettojezuz** [comment]
Та же проблема при миграции с 13 версии
Но я даже не обратил внимания на то, что тесты не выполняются)

**Comment by andreynovikov95** [comment]
1. Нужно прописать настройки в проекте для Jest:
```
  "jest": {
    "preset": "arui-scripts",
    "testEnvironment": "jsdom",
    "setupFilesAfterEnv": [
      "./__tests__/setup.ts"
    ],
   ...
}
```
2. Для Jest v26, c arui-scripts < 14.0.0 установить в devDependencies
"jest-environment-jsdom": " 26.6.2",
Для Jest v28 
"jest-environment-jsdom": " 28.1.3",
3. Содержание файла `./__tests__/setup.ts`
```
import { configure } from 'enzyme';
import Adapter from '@wojtekmaj/enzyme-adapter-react-17';

configure({ adapter: new Adapter() });
window.React = require('react');
```
4. Установить в devDependencies @wojtekmaj/enzyme-adapter-react-17 при использовании React 17
Если используется в React v16, то можно не указывать setupFilesAfterEnv и не устанавливать @wojtekmaj/enzyme-adapter-react-17

**Comment by Rinta01** [comment]
@andreynovikov95 что-то странное количество телодвижений нужно, чтобы заработал дефолтный setupFile. Он должен работать без установки доп. пакетов, или же эти доп пакеты должны быть включены в peerDependencies, а доп конфиги по умолчанию стоять в конфге jest в arui-scripts.
Так получается, что предложенное решение - просто "заглушка"

**Comment by andreynovikov95** [comment]
думаю да, jest-environment-jsdom можно было бы добавить в arui-scripts с "testEnvironment": "jsdom". По поводу адаптера, тут от проекта зависит, какую версию React используют
