### ISSUE TITLE
Удаление Enzyme из зависимостей

### ISSUE THREAD

**Issue by andreynovikov95** [core-ds/arui-scripts#29]
После перехода на React 18 нет поддержки Enzyme, последняя доступная версия через неофициальный пакет для React 17, которая тоже перестала развиваться https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl.

Предлагаю удалить адаптер Enzyme с [файлом](https://github.com/core-ds/arui-scripts/blob/master/packages/arui-scripts/src/configs/jest/setup.js). В рекомендациях Readme написать использование [react-testing-library](https://github.com/kentcdodds/react-testing-library) для тестирования DOM. И для снепшотного тестирования [react-test-renderer](https://www.npmjs.com/package/react-test-renderer). [Примеры](https://jestjs.io/ru/docs/tutorial-react#%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-dom)

**Comment by Rinta01** [comment]
Если я правильно понял твое предложение, то в таком случае нужно явно избавляться от поддержки react@<18, что отсечет довольно большое кол-во проектов

**Comment by andreynovikov95** [comment]
Не совсем, не предлагаю избавляться от поддержки React < 18, поскольку библиотека [react-test-renderer](https://www.npmjs.com/package/react-test-renderer) добавлена еще в версии [15.3.0](https://github.com/facebook/react/blob/main/CHANGELOG.md#1530-july-29-2016). Официально сейчас доступна документация для React 17 и 18, возможно есть и в более ранних версиях. Нашел примеры в Jest [для React 17](https://github.com/jestjs/jest/blob/v28.1.3/examples/react-testing-library/package.json) и для [более ранних](https://github.com/jestjs/jest/blob/v27.5.1/examples/react-testing-library/package.json). И библиотека [react-testing-library](https://github.com/kentcdodds/react-testing-library) имеет поддержку React < 18 [12.1.5](https://github.com/testing-library/react-testing-library/releases/tag/v12.1.5) и с v13 ([13.0.0](https://github.com/testing-library/react-testing-library/releases/tag/v13.0.0)) React 18.

Сейчас в arui-scripts поддержка только React 16. Надо бы выполнить миграцию на новые библиотеки, которые поддерживают в том числе React 17. И подумать как привнести поддержку React 18. Возможно, выпустить новую версию с обновлением их версий, либо придумать какую-то дополнительную настройку

**Comment by andreynovikov95** [comment]
Ещё сейчас в arui-scripts перешли на Jest 28, который поддерживает React 17. То есть для того, чтобы переходить на тестирование React 18 нужно еще дообновить Jest на 29ую версию

**Comment by sklyanchuk** [comment]
Как вариант: вынести из arui-scripts компонентное тестирование и писать его на Cypress?
