### ISSUE TITLE
Типизация useEventBusValue и getEventBus

### ISSUE THREAD

**Issue by artyomSultanov** [core-ds/arui-scripts#292]
https://github.com/core-ds/arui-scripts/blob/133686a1e02430bc7e42861cc4a4ec3c467d3eef/packages/client-event-bus/src/use-event-bus-value.ts#L9

Метод `getEventBus` возвращает `AbstractAppEventBus<AbstractKnownEventTypes> | null`, в то время как `useEventBusValue` принимает в качестве параметра `eventBus` типа `AbstractAppEventBus<AbstractKnownEventTypes> | undefined`. Из-за разного union-типа приходится накидывать свой код а-ля `?? undefined`. Можно ли как-то синхронизировать типы этих методов?

**Comment by heymdall-legal** [comment]
https://github.com/core-ds/arui-scripts/releases/tag/%40alfalab%2Fclient-event-bus%402.0.2 - релиз с фиксом
