### ISSUE TITLE
Добавить поддержку image-minimizer-webpack-plugin

### ISSUE THREAD

**Issue by andreynovikov95** [core-ds/arui-scripts#37]
Лучше добавить минимайзер image-minimizer-webpack-plugin, который может содержать как svgo плагин, так и другие форматы изображений: jpeg, png, gif. Обычно картинки используются в баннерах

Настройки https://webpack.js.org/plugins/image-minimizer-webpack-plugin/#optimize-with-imagemin
![Выделение_707](https://github.com/core-ds/arui-scripts/assets/64052598/496bb982-d80a-473f-adb2-171d9fb87987)

**Comment by vaagnavanesyan** [comment]
Нужно добавить возможность включать/выключать сжатие через конфиг arui-scripts + управлять вариантом включения графики в бандл: инлайн или ассеты. Сейчас этот выбор делается на основе размера файла
