### ISSUE TITLE
Невозможно установить пакеты без доступа к сети Интернет.

### ISSUE THREAD

**Issue by Hydrock** [core-ds/arui-scripts#46]
В одном из последних коммитов была добавлена возможность настроить минификацию изображений и в том числе gif

Если пакеты ставятся из закрытого registry - то возникает проблема при установке пакета gifsicle
Он пытается запросить интернет адрес и получает ожидаемую ошибку:

```
19:13:14  Output:
19:13:14  connect ETIMEDOUT 185.199.108.133:443
19:13:14  gifsicle pre-build test failed
19:13:14  compiling from source
19:13:14  Error: Command failed: /bin/sh -c autoreconf -ivf
19:13:14  /bin/sh: 1: autoreconf: not found
```

https://github.com/imagemin/gifsicle-bin/blob/main/lib/index.js#L7

В данной библиотеке зашит интернет адрес. Кажется что лучшим решением будет пока отказаться от данной библиотеки.

**Comment by vaagnavanesyan** [comment]
К сожалению, такая же ситуация обстоит с пакетом `mozjpeg`, поэтому придется поискать решение. Возможно, бандлить необходимые бинарники вместе с `arui-scripts` или как-то еще
