### ISSUE TITLE
Проблема при парсинге конфига с Typescript@>=4.7

### ISSUE THREAD

**Issue by Rinta01** [core-ds/arui-scripts#5]
**Описание проблемы:**
При запуске проекта возникает критическая ошибка при сборке во время парсинга файла конфига (с использованием npm-пакета 'config').
![image](https://user-images.githubusercontent.com/25585138/230453495-6d8f154f-94e5-4cf6-aadd-8a494ed30cac.png)

**Воспроизводится при следующих зависимостях:**
```
arui-scripts@14.0.0
NodeJS 16.16.0
typescript@4.8.2
```

**Возможное решение:**
Проблема решается апгрейдом версии ts-node и ts-loader? (мне хватило только ts-node, но пишут что второе тоже нужно).  
Достаточные версии пакетов для корректной работы:  
```
"ts-loader": "9.4.2",
"ts-node": "10.9.1"
```
Проблему так же решает даунгрейд версии TS до версии ниже 4.7, но это как решение, на мой взгляд, не стоит рассматривать

**Актуальные ссылки:**
https://stackoverflow.com/questions/72488958/false-expression-non-string-value-passed-to-ts-resolvetypereferencedirective

**Comment by Echzio** [comment]
Привет! С кофигом ты работаешь в рантайме на стороне сервера, при помощи ts-node, почему сложилось впечатление что проблема в arui-scripts?

**Comment by Rinta01** [comment]
Привет
Проблема в версии ts-node, которая идет в зависимостях скрипта. Чтобы все работало с последними версиями ТС нужно самостоятельно устанавливать более новую версию ts-node. Понимаю, что использование одной библиотеки (config) не обосновывает апдейт зависимости библиотеки, но это флаг, что похожие проблемы могут возникнуть при работе с другими пакетами.

**Comment by Echzio** [comment]
Понял, попробую разобраться

**Comment by Rinta01** [comment]
Есть какие-то апдейты? Очень жду фикс

**Comment by Echzio** [comment]
Привет! Сори за долгое ожидание, мне не удалось воспроизвести проблему, можем как-то связаться, чтобы ты написал название проекта и шаги для воспроизведения?

**Comment by Rinta01** [comment]
@me_rinta в телеге
давай там спишемся

**Comment by Echzio** [comment]
Привет!
Удалось воспроизвести проблему, но, в дополнение к моему сообщению выше - не устанавливая ts-node, ты его используешь как транзитивную зависимость из arui-scripts. Если ты хочешь использовать node-config вместе с typescript, все таки тебе нужно поставить ts-node в свой проект. В качестве обходного пути без установки ts-node ты можешь добавить флаг «transpileOnly» в твой tsconfig.json:


```
{
  …,
  «extends»: …,
  «include»: …,
  …,
  "ts-node": {
    "transpileOnly": true,
  },
  …,
}
```


Это избавит тебя от ошибки, используя транзитивный ts-node@9.1.1 (проверка типов через ts-node по большей части не нужна из за проверки в ide + fork-ts-checker-webpack-plugin). Но если в какой то момент в arui-scripts откажутся от ts-node, то все равно придется тянуть в его в проект, или переехать на https://github.com/tusharmath/node-config-ts

**Comment by Rinta01** [comment]
Привет
Проблему мою, судя по твоим комментариям, действительно стоит решать установкой отдельной версии, которая нужна именно мне, не опираясь на версию из arui-scripts, но я тогда не очень понимаю тогда зачем на данный момент ts-node в проекте используется и почему его нельзя апгрейднуть (какие в этом минусы и есть ли они)
