### ISSUE TITLE
Нарушение порядка импорта css-файлов при использовании React.lazy

### ISSUE THREAD

**Issue by vaagnavanesyan** [core-ds/arui-scripts#50]

**Comment by Echzio** [comment]
https://github.com/facebook/create-react-app/issues/5372

**Comment by vaagnavanesyan** [comment]
https://github.com/facebook/create-react-app/issues/5372#issuecomment-995632657

**Comment by vaagnavanesyan** [comment]
Проблема воспроизводится на проектах, использующих arui-scripts 13.1.0 и ниже. После апгрейда до 13.1.1 проблема разрешилась
