### ISSUE TITLE
Отсутствует файл configs/jest/setup

### ISSUE THREAD

**Issue by Rinta01** [core-ds/arui-scripts#73]
https://github.com/core-ds/arui-scripts/blob/master/packages/arui-scripts/jest-preset.js#L17

Файл, указанный в jest-config.js, отсутствует в проекте. В одном из проектов VS Code это заметил и выдал ошибку, а в других почему-то нет

**Comment by vaagnavanesyan** [comment]
А у проектов одинаковая версия arui-scripts ? И есть ли какие-либо оверрайды на уровне проекта?

**Comment by Rinta01** [comment]
Версию одну и ту же поставил - 15.2.0. Оверрайды тоже пытался те же самые делать - все то же самое.
Но проблема кажется не сильно сейчас даже в проекте - файла то действительно нет. Кажется, что даже если IDE не ругается, то это скорее ошибка.
