### ISSUE TITLE
Проблема с keepCssVars и componentsTheme в 15.5.2

### ISSUE THREAD

**Issue by sanityFair** [core-ds/arui-scripts#97]
При обновлении забыли подтянуть postcss конфиг из версии 15.0.0.

**Comment by heymdall-legal** [comment]
"проблема" звучит очень абстрактно. В 15.0.0 были баги с postcss конфигурацией, поправленные например тут
https://github.com/core-ds/arui-scripts/pull/64

Про какие именно проблемы идет речь?

**Comment by sanityFair** [comment]
@heymdall-legal
Я полагал, что keepCssVars использует медиа переменные из файла и аналогично переменных из componentsTheme.
После обновления  изменился механизм добавления, чтобы  не импортировать определения пользовательских свойств в каждый файл используется PostCSS Global Datа, который идет перед custom-properties.
`( config.componentsTheme || config.keepCssVars ) && '@csstools/postcss-global-data',
    config.keepCssVars && 'postcss-custom-media',
    config.componentsTheme && 'postcss-custom-properties',`

**Comment by khidirbekov** [comment]
@heymdall-legal приветствую! Я правильно понимаю, что `keepCssVars: false` (postcss-custom-properties: { preserve: false }) означает, что из бандла должны выпилиться все переменные?

**Comment by heymdall-legal** [comment]
да, предполагается что это для случаев, когда css-переменные не поддерживаются. К сожалению все еще есть ряд проектов, в которых надо поддерживать ie11

**Comment by khidirbekov** [comment]
сейчас получается, что этот параметр не работает. На выходе остаются переменные 
![image](https://github.com/core-ds/arui-scripts/assets/39237435/2db3adfe-23fe-46b4-b4b0-1f1b0a1fa6d4)
и причем они дублируются (проблема с дублированием уже скорее решается другим плагином)

**Comment by sanityFair** [comment]
> сейчас получается, что этот параметр не работает. На выходе остаются переменные ![image](https://user-images.githubusercontent.com/39237435/263213877-2db3adfe-23fe-46b4-b4b0-1f1b0a1fa6d4.png) и причем они дублируются (проблема с дублированием уже скорее решается другим плагином)

Это плагин не решает проблему с дублированием переменных - postcss-discard-duplicates. Во всех компонентах кора есть свой рут

**Comment by khidirbekov** [comment]
> > сейчас получается, что этот параметр не работает. На выходе остаются переменные ![image](https://user-images.githubusercontent.com/39237435/263213877-2db3adfe-23fe-46b4-b4b0-1f1b0a1fa6d4.png) и причем они дублируются (проблема с дублированием уже скорее решается другим плагином)
> 
> Это плагин не решает проблему с дублированием переменных - postcss-discard-duplicates. Чтобы не дублировались root переменные, лучше добавлять тему для глобального доступа global data

Я про сам параметр keepCssVars, сейчас он не работает как должно работать

**Comment by heymdall-legal** [comment]
Исправлено в `arui-scripts` версии [15.7.1](https://github.com/core-ds/arui-scripts/releases/tag/arui-scripts%4015.7.1)
