### ISSUE TITLE
Не очищаются дубликаты из бандла

### ISSUE THREAD

**Issue by khidirbekov** [core-ds/arui-scripts#99]
Приветствую!
Недавно обновились с arui-scripts 14.9.0 до 15.5.2 и столкнулись с тем, что в файле css очень много кода дублируется, а именно импорты переменных (скрин)
![image](https://github.com/core-ds/arui-scripts/assets/39237435/b3db02d3-28b0-4352-94d4-8fa4eaf965e9)
В раних версиях мы это решали с использованием `keepCssVars: false`, все переменные тупо выпиливались.
С обновлением `keepCssVars` перестало работать удаление переменных и при разработке подвисает консоль разработки из-за громоздкого файла.

В идеале хотелось бы добавление поддержки плагина удаления дубликатов (postcss-discard-duplicates) + исправление поведения keepCssVars и в дев и прод режиме.

postcss конфиг: 
```
postcss: () => {
        const options = {
            ...postcssPluginsOptions,
            'postcss-import': {
                ...postcssPluginsOptions['postcss-import'],
                path: postcssPluginsOptions['postcss-import'],
                resolve: resolver({
                    alias: {
                        '@common': path.resolve('./src/common/styles'),
                    },
                }),
            },
        };

        return createPostcssConfig(postcssPlugins, options);
    },
```

**Comment by sanityFair** [comment]
@khidirbekov Привет, Уточни, пожалуйста, а при сборки дубликаты остаются?

**Comment by heymdall-legal** [comment]
Дубликат #97, решение будет там
